export const ADD_TOPIC = 'ADD_TOPIC';
export const FILTER_TOPIC = 'FILTER_TOPIC';
export const REMOVE_TOPIC = 'REMOVE_TOPIC';
export const SET_TPCS_CHANGED = 'SET_TPCS_CHANGED';
export const SET_CURRENT_CARD = 'SET_CURRENT_CARD';
export const SET_ACTIVE_FORM = 'SET_ACTIVE_FORM';
